# This is an input file for the diagonalization routine. The format is YAML,
# which is quite flexible.
L : [2,2,2]
gauge_particles : 'bosons'
# 'winding_sector' : (0,0)
full_diag : False
ev_type : 'BE'
n_eivenvalues : 100
lambda : 0
J : -1.0
